### PR TITLE
Firefox on travis

### PR DESCRIPTION
**Pull request by thraxil**
Not sure we actually want to merge this. Mostly putting it up to start discussion.

Looks TravisCI actually makes it pretty straightforward to run Firefox so we could do full browser testing. Since DMT already had Karma and PhantomJS set up, I used it as a test to get it to just run the tests against Firefox instead of PhantomJS and it seems to work.

This is encouraging as far as making it likely that I'm willing to put more time and effort into getting a Selenium testing setup back (but almost certainly dropping Lettuce in favor of Behave for any BDD stuff).

### CODE REVIEW

**Comment by nikolas** [comment]
That's cool - it would be good to get some integration, selenium-style testing working with firefox and chrome. For the karma unit tests, I would prefer to stick to phantomjs because I don't know if the benefits of running these tests on firefox outweighs having another dependency and something else to think about.

**Comment by coati-00** [comment]
Sorry :(

**Comment by coati-00** [comment]
Merged this after looking at changed files, missed the comment on how it was for discussion not merging :-/    I didn't delete the branch so I guess just do another pull request? Sorry...

**Comment by nikolas** [comment]
Hey it's cool @coati-00. Now it's clear we'd need to install firefox on our jenkins server if we were to add in browser testing to karma, or configure it to not run those tests on jenkins.

**Pull request merged**
