### PR TITLE
Hide and log 500 error on send_mail() call

### PR DESCRIPTION
**Pull request by nikolas**
https://sentry.ccnmtl.columbia.edu/sentry-internal/dmt/group/1148/

### CODE REVIEW

**Comment by nikolas** [comment]
Paul received this error when assigning a PMT to a new user. More info here:
https://pmt.ccnmtl.columbia.edu/item/107446/#event-5

**Comment by thraxil** [comment]
It looks like the root cause though is that users are getting in without an email address. I'd almost rather prefer that the PMT loudly 500s if it's unable to send email out. Hiding it means that items go in (or other ones get updated), but the user is never notified. Long term, that could cause more confusion than the PMT giving a 500 and refusing to add the item right from the beginning.

**Comment by sdreher** [comment]
Should we think about preventing or warning about the missing email too? The Django admin lets users be created without emails. But for mail-centric PMT, this state should be highlighted as an error.

**Comment by nikolas** [comment]
Yeah, it looks like the user's `userprofile.email` field is blank, which is causing the problem. I'll fix the root cause, but I do feel like we should prevent 500 errors from the user even in critical circumstances - possibly showing a more user-friendly error like "User was not notified".

**Pull request closed without merging**
