### PR TITLE
:arrow_up: django 1.8.6

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by thraxil** [comment]
looks like it needs django-celery updated first

**Comment by nikolas** [comment]
Now there's a south migration issue in the django-oauth2-provider package, which we might have to fork since their repository isn't that responsive.

**Comment by nikolas** [comment]
According to some of the discussion (https://github.com/caffeinehit/django-oauth2-provider/pull/113), django-oauth2-provider isn't maintained anymore. I'll look into switching to [django-oauth-toolkit](https://github.com/evonove/django-oauth-toolkit).

**Comment by nikolas** [comment]
This is passing now that we don't have django-oauth2-provider in dmt anymore.

**Pull request merged**
