### PR TITLE
Allow multiple users in action item "Assigned To" - PMT #103673

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by sdreher** [comment]
First - very cool that you're addressing this one. Multiple assignees is an old wish list item.

And - question - is this the first step in dealing with multiple assignees? I'm not seeing changes in the item view to reflect multiple users being assigned work, or the ability to add/edit/delete assignees.

**Comment by nikolas** [comment]
The change is in the "Add Action Item" modal, when you click "Add action item" on the project detail page: 
screen shot 2016-02-03 at 10 09 34 am

**Comment by nikolas** [comment]
This isn't a change for a single PMT to have multiple assignees... it's really the ability to create multiple duplicate PMTs each assigned to a different person. This is kind of confusing, is there a way we could make this clearer?

**Comment by sdreher** [comment]
Ah, okay. I was (wishfully) thinking this was the beginnings of a collaborative task. Maybe some sort of messaging before or after save that indicates "4 PMTs will be created" might help clarify what's happening?

**Comment by nikolas** [comment]
good idea, i'll add that

**Comment by nikolas** [comment]
I've added a notice when more than one assignee is selected:
2016-02-03-142226_302x130_scrot

**Pull request merged**
