### PR TITLE
Removes Celery, RabbitMQ, and Chat

### PR DESCRIPTION
**Pull request by nbuonin**
This commit pulls the above functionality from the app.

### CODE REVIEW

**Comment by nikolas** [comment]
@nbuonin can you update this PR to only include the removal of Celery, etc?

The python 3 stuff is failing in travis, and can be addressed in a separate change set.

**Comment by nbuonin** [comment]
@nikolas sure, I'll roll it back to the commit prior to the travis changes.

**Comment by nikolas** [comment]
there are still some references to celery and rabbitmq in the codebase... i'll clean those up.

**Comment by nbuonin** [comment]
thanks @nikolas

**Comment by nikolas** [comment]
No, thank you for the best kind of pull request: I love removing things! haha.

**Pull request merged**
