### PR TITLE
Update to Django 1.8

### PR DESCRIPTION
**Pull request by nikolas**
https://docs.djangoproject.com/en/1.8/releases/1.8/

### CODE REVIEW

**Comment by thraxil** [comment]
Yeah, I started converting some personal sites and found that quite a few django apps (eg, django-nose: https://github.com/django-nose/django-nose/issues/186) still aren't compatible with 1.8.

**Comment by nikolas** [comment]
Yeah it looks like django-nose needs to refactor some code from `optparse` to `argparse`. In the meantime I've been looking to see if we can sidestep the issue by using django-nose2.

**Comment by nikolas** [comment]
Now that we're no longer using django-nose in DMT, we can avoid those problems.

But there's a new problem -- now the tests are failing when setting up the test db:
```
django.db.utils.ProgrammingError: relation "auth_user" does not exist
```

https://travis-ci.org/ccnmtl/dmt/builds/59028083

**Comment by thraxil** [comment]
Interesting. factory_boy, perhaps? I remember having to do things in slightly weird ways to get it to create auth.User's and UserProfile's. Good chance that whatever I did is now too weird for 1.8.

**Comment by nikolas** [comment]
I fixed the `auth_user` error by creating an external migration for the oauth2 provider as described here: https://github.com/evonove/django-oauth-toolkit/issues/204#issuecomment-77984967

New error is:
```
ValueError: Related model u'main.User' cannot be resolved
File "/home/travis/build/ccnmtl/dmt/dmt/main/migrations/0010_auto_20150126_0732.py", line 27,
in populate_notify
    for n in Notify.objects.all():
```
Caused by one of our migrations
https://travis-ci.org/ccnmtl/dmt/builds/59606474#L1031

**Comment by nikolas** [comment]
It looks like django 1.8.1 might have resolved that issue -- now there's a few errors to look into within our tests.

**Comment by nikolas** [comment]
Those errors are fixed now -- Django 1.8 raises an exception when the arguments given to `select_related()` are invalid. I fixed those in this commit: 34e30a300babd9591f7de839d012b3013f222376

**Pull request merged**
