### PR TITLE
bdd tests for adding a new project

### PR DESCRIPTION
**Pull request by thraxil**

### CODE REVIEW

**Comment by thraxil** [comment]
argh. behave tests are running reliably locally. haven't been able to duplicate the "StaleElementReferenceException" anywhere but on Travis...

Has anyone ever gotten anything involving selenium to run reliably?

**Comment by sdreher** [comment]
The Meth tests run reliably in my local env. Not much help I know.

**Comment by nikolas** [comment]
When I've used Selenium in the past, the tests seemed to inevitably require a bunch of `sleep 1` statements throughout the tests, as ugly as it is, and lots of trial and error.

**Comment by thraxil** [comment]
That's what I did on the last commit. No difference.

**Comment by sdreher** [comment]
Nothing that at some point, you also suggested the try/except/sleep pattern. This approach has worked well in Meth and generally has prevented the direct/fragile sleeps.  

Seriously though, with a 5 second implicit sleep, that should really be enough.

**Comment by thraxil** [comment]
fffffffff.....

OK. Looks like the main culprit may have just been the FF version (slightly newer than what selenium 2.44 was built against, but not enough for it to break outright). Going to  close this out, squash the commits, and make a new PR.

**Pull request closed without merging**
